#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.TreeView.Resource", IsApplication=false)]

namespace Xamarin.TreeView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public static int head_margin = 2130771973;
			
			// aapt resource value: 0x7f010006
			public static int maxLevel = 2130771974;
			
			// aapt resource value: 0x7f010004
			public static int node_margin = 2130771972;
			
			// aapt resource value: 0x7f010001
			public static int trace_color = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int trace_margin = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int trace_visibility = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int trace_width = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int invisible = 2130968576;
			
			// aapt resource value: 0x7f040003
			public static int treeview_listitem_wrapper_container = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int treeview_listitem_wrapper_root = 2130968578;
			
			// aapt resource value: 0x7f040004
			public static int treeview_listitem_wrapper_trace = 2130968580;
			
			// aapt resource value: 0x7f040001
			public static int visible = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int treeview_listitem_wrapper = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TreeView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 5
			public static int TreeView_head_margin = 5;
			
			// aapt resource value: 6
			public static int TreeView_maxLevel = 6;
			
			// aapt resource value: 4
			public static int TreeView_node_margin = 4;
			
			// aapt resource value: 1
			public static int TreeView_trace_color = 1;
			
			// aapt resource value: 3
			public static int TreeView_trace_margin = 3;
			
			// aapt resource value: 0
			public static int TreeView_trace_visibility = 0;
			
			// aapt resource value: 2
			public static int TreeView_trace_width = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
