version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/Xamarin.TreeView/Xamarin.TreeView"
    update_schedule: "weekly"
    target_branch: "devel"
    default_reviewers:
    - Guiorgy
    default_assignees:
    - Guiorgy
    default_labels:
    - "dependabot"
    ignored_updates:
      - match:
        dependency_name: "Xamarin.Android.Support.v7.RecyclerView"

  - package_manager: "dotnet:nuget"
    directory: "/Xamarin.TreeView/DemoApp"
    update_schedule: "weekly"
    target_branch: "devel"
    default_reviewers:
    - Guiorgy
    default_assignees:
    - Guiorgy
    default_labels:
    - "dependabot"